
FROM nginx:1.12-alpine
COPY ./greet.json /usr/share/nginx/html
COPY ./conf/api-app.conf /etc/nginx/conf.d/default.conf
COPY ./conf/startNginx.sh /etc/nginx/startNginx.sh
EXPOSE 80
CMD ["sh","/etc/nginx/startNginx.sh"]
